modLoader="javafml"
loaderVersion="[47,)"
license="All Rights Reserved"

[[mods]]
modId="invincible"
version="3"
displayName="Invincible"
displayURL="https://discord.gg/gHqRUE4ecb"
logoFile="logo.png"
credits="sushiclozy, NoiiLive, Invincible"
authors="sushiclozy, NoiiLive"
description="Adds Invincible into Minecraft"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.invincible]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="AFTER"
    side="BOTH"


[[dependencies.invincible]]
    modId="kleidersplayerrenderer"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.invincible]]
    modId="geckolib"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.invincible]]
    modId="playeranimator"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"


# Start of user code block dependencies configuration
# End of user code block dependencies configuration